set public Key

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -113,36 +113,53 @@ jobs:
         run: |
           echo "${{ secrets.EC2_SSH_KEY }}" | > promaKey.pem
           chmod 600 promaKey.pem
-
-      - name: Deploy Docker container to EC2
-        run: |
-          ssh -tt -i promaKey.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
-            # Stop and remove the existing Docker container if it exists
-            if sudo docker ps -q -f name=proma > /dev/null; then
-              echo "Stopping and removing existing proma container"
-              sudo docker stop proma
-              sudo docker rm proma
-            fi
-
-            # Pull the latest image
-            echo "Pulling new image"
+                
+      - name: pull private repository
+        uses: appleboy/ssh-action@v0.1.10
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.DEPLOY_SSH_KEY }}
+          port: ${{ secrets.PORT }}
+          script_stop: true
+          script: |
+            sudo docker stop proma
+            sudo docker rm proma
             sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/proma
-
-            # Run a new container from the pulled image
-            echo "Running new container"
             sudo docker run -d -p 8080:8080 --name proma ${{ secrets.DOCKERHUB_USERNAME }}/proma
-
-            # Clean up unused Docker resources
-            echo "Cleaning up unused Docker resources"
             sudo docker system prune -f
-
-            # Stop the existing Java application if running
             pgrep java | xargs kill -9 || true
-
-            # Run the new Java application
-            echo "Running new Java application"
             nohup java -jar /home/${{ secrets.EC2_USERNAME }}/proma.jar > app.log 2>&1 &
-          EOF
+
+      # - name: Deploy Docker container to EC2
+      #   run: |
+      #     ssh -tt -i "${{ secrets.EC2_SSH_KEY }}" -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
+      #       # Stop and remove the existing Docker container if it exists
+      #       if sudo docker ps -q -f name=proma > /dev/null; then
+      #         echo "Stopping and removing existing proma container"
+      #         sudo docker stop proma
+      #         sudo docker rm proma
+      #       fi
+
+      #       # Pull the latest image
+      #       echo "Pulling new image"
+      #       sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/proma
+
+      #       # Run a new container from the pulled image
+      #       echo "Running new container"
+      #       sudo docker run -d -p 8080:8080 --name proma ${{ secrets.DOCKERHUB_USERNAME }}/proma
+
+      #       # Clean up unused Docker resources
+      #       echo "Cleaning up unused Docker resources"
+      #       sudo docker system prune -f
+
+      #       # Stop the existing Java application if running
+      #       pgrep java | xargs kill -9 || true
+
+      #       # Run the new Java application
+      #       echo "Running new Java application"
+      #       nohup java -jar /home/${{ secrets.EC2_USERNAME }}/proma.jar > app.log 2>&1 &
+      #     EOF
 
       - name: Clean up SSH key
         run: |
